---
# GOLDEN IMAGE PLAYBOOK
- hosts: all
  become: true

# ////////////////////////////////////////////////////////////////////////////////////////
#  VARIABLES
# ////////////////////////////////////////////////////////////////////////////////////////
  vars_files:
  - "./golden_vars.yml"

# ////////////////////////////////////////////////////////////////////////////////////////
#  ENVIRONMENT VARIABLES
# ////////////////////////////////////////////////////////////////////////////////////////
  environment:
    # ANSIBLE_HOST: "{{ inventory_hostname }}"

# ////////////////////////////////////////////////////////////////////////////////////////
#  TASKS
# ////////////////////////////////////////////////////////////////////////////////////////
  tasks:

  # EXECUTE ROLES //////////////////////////////////////////////////////////////////////
    - name: Include RHEL Role
      include_role:
        name: rhel
      when: role_selector == "rhel"
      tags:
          - rhel

    - name: Include WINDOWS Role
      include_role:
        name: windows
      when: role_selector == "windows"
      tags:
          - windows
    
    - name: Include RUNNER Role
      include_role:
        name: runner
      when: role_selector == "runner"
      tags:
          - runner


