---
# RHEL GOLDEN IMAGE PLAYBOOK
- hosts: all
  become: true

# ////////////////////////////////////////////////////////////////////////////////////////
#  VARIABLES
# ////////////////////////////////////////////////////////////////////////////////////////
  vars_files:
  - "./rhelPlaybookVars.yaml"

  # vars:

# ////////////////////////////////////////////////////////////////////////////////////////
#  ENVIRONMENT VARIABLES
# ////////////////////////////////////////////////////////////////////////////////////////
  environment:
    # ANSIBLE_HOST: "{{ inventory_hostname }}"

# ////////////////////////////////////////////////////////////////////////////////////////
#  TASKS
# ////////////////////////////////////////////////////////////////////////////////////////
  tasks:

  # GRAB ACCOUNTS //////////////////////////////////////////////////////////////////////
    - name: Include CIS Role
      include_role:
        name: mindpointgroup.rhel7_cis
      when: cis_hardening

    - name: Run Script for Image Configuration
      shell:
      args:
        executable: /usr/bin/bash
        cmd: bash runnerScript.sh
        chdir: ./
      # register: accounts_inventory
      # when: (key1 == "value1") and (key2 == "value2")
    - debug:
        var: results.stdout
