---
# RHEL GOLDEN IMAGE PLAYBOOK
- hosts: all
  become: true

# ////////////////////////////////////////////////////////////////////////////////////////
#  VARIABLES
# ////////////////////////////////////////////////////////////////////////////////////////
  vars_files:
  - "./rhelPlaybookVars.yaml"

  # vars:

# ////////////////////////////////////////////////////////////////////////////////////////
#  ENVIRONMENT VARIABLES
# ////////////////////////////////////////////////////////////////////////////////////////
  environment:
    # ANSIBLE_HOST: "{{ inventory_hostname }}"

# ////////////////////////////////////////////////////////////////////////////////////////
#  TASKS
# ////////////////////////////////////////////////////////////////////////////////////////
  tasks:

  # GRAB ACCOUNTS //////////////////////////////////////////////////////////////////////
    - name: Include CIS Role
      include_role:
        name: rhel7_cis
      when: cis_hardening
      tags:
          - cis_hardening

    - name: Run Script for Image Configuration
      shell: bash ./rhelScript.sh
      args:
        executable: /usr/bin/bash
      tags:
          - configuration_script
      # register: accounts_inventory
      # when: (key1 == "value1") and (key2 == "value2")


