---
# RHEL GOLDEN IMAGE PLAYBOOK
- hosts: all
  become: true

# ////////////////////////////////////////////////////////////////////////////////////////
#  VARIABLES
# ////////////////////////////////////////////////////////////////////////////////////////
  vars_files:
  - "./rhelPlaybookVars.yaml"

# ////////////////////////////////////////////////////////////////////////////////////////
#  ENVIRONMENT VARIABLES
# ////////////////////////////////////////////////////////////////////////////////////////
  environment:
    # ANSIBLE_HOST: "{{ inventory_hostname }}"

# ////////////////////////////////////////////////////////////////////////////////////////
#  TASKS
# ////////////////////////////////////////////////////////////////////////////////////////
  tasks:

  # GRAB ACCOUNTS //////////////////////////////////////////////////////////////////////
    - name: Run Script for Image Configuration
      command: sleep 30 && sudo yum -y update
      register: init_logs
      when: init_instance
      tags:
          - init_instance

    - name: Include CIS Role
      include_role:
        name: rhel7_cis
      when: cis_hardening
      tags:
          - cis_hardening

    - name: Run Script for Image Configuration
      shell: rhelScript.sh
      register: configuration_logs
      when: configuration_script
      tags:
          - configuration_script


