---
# WINDOWS GOLDEN IMAGE PLAYBOOK
- hosts: localhost
  become: true

# ////////////////////////////////////////////////////////////////////////////////////////
#  VARIABLES
# ////////////////////////////////////////////////////////////////////////////////////////
  vars_files:
  - "./windowsPlaybookVars.yaml"

  # vars:

# ////////////////////////////////////////////////////////////////////////////////////////
#  ENVIRONMENT VARIABLES
# ////////////////////////////////////////////////////////////////////////////////////////
  environment:
    # ANSIBLE_HOST: "{{ inventory_hostname }}"

# ////////////////////////////////////////////////////////////////////////////////////////
#  TASKS
# ////////////////////////////////////////////////////////////////////////////////////////
  tasks:

# ////////////////////////////////////////////////////////////////////////////////////////
#  GRAB ACCOUNTS
# //////////////////////////////////////////////////////////////////////////////////////// 

  # GRAB ACCOUNTS //////////////////////////////////////////////////////////////////////
    - name: Run Script for Image Configuration
      shell:
      args:
        executable: /usr/bin/bash
        cmd: bash runnerScript.sh
        chdir: ./
      register: accounts_inventory
      # when: (key1 == "value1") and (key2 == "value2")
    # - debug:
    #     var: results.stdout

  # LOCAL TEST //////////////////////////////////////////////////////////////////////////
#     - name: Write results to local output file (DEV)
#       copy:
#         dest: "./output/accounts_inventory_output.json"
#         content: "{{inventory_hostname}}: {{accounts_inventory}}"
#       when: dev
#       # delegate_to: localhost


# - hosts: localhost
#   gather_facts: false
#   vars_files:
#   - "./vars.yaml"
#   tasks:
#     - name: Write results to local output file (PRODUCTION)
#       copy:
#         dest: "./output/accounts_inventory_output.json"
#         content: |
#           {% for host in all %}
#           === {{ host }} ==

#           {{hostvars[host].accounts_inventory}}

#           {% endfor %}
#       when: not dev

#     - name: Upload/PUT file to S3 bucket
#       amazon.aws.aws_s3:
#         profile: personal
#         bucket: inventory
#         mode: put
#         object: "{{ ansible_date_time.iso8601 }}-{{file_output}}.json"
#         src: "/output/{{file_output}}.json"
#       when: not dev