---

- include: init_instance/main.yml
  when: init_instance
  tags:
      - init_instance

- include: cis_hardening/main.yml
  when: cis_hardening
  tags:
      - cis_hardening

- include: image_configuration/main.yml
  when: image_configuration
  tags:
      - image_configuration

- include: stig_hardening/main.yml
  when: stig_hardening
  tags:
      - stig_hardening
